### PR TITLE
Add graph scaling

### PR DESCRIPTION
**Pull request by fedorcomander**
Hi guys!

Just added graph scaling tool. You can scale from 0.1 up to 20. Looks actually kinda nice. Well, Nik will decide to add it or not as usual.

screen shot 2015-06-10 at 16 59 10

### CODE REVIEW

**Comment by borisbstyle** [comment]
It would be nice to be able to decrease the jumps once zoomed.
You know when you want to manually put it on some part of the graph it jumps 100msec further now and it should be less once zoomed in to keep it in proportions.

**Comment by fedorcomander** [comment]
Drag  top chart for fine tuning. Jump from bottom chart goes to same position as before due to same scale of the bottom chart  - same amount of steps (pixels) in it.

**Comment by borisbstyle** [comment]
Thank....I never realized the top chart could be dragged :blush:

**Comment by thenickdude** [comment]
Thanks, I've changed the scale control to a percentage zoom.

**Comment by fedorcomander** [comment]
You are the boss ;) Thanks mate.

**Pull request merged**
